name: Run Python Script on Multiple Platforms

on: [push]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: pip install psycopg2-binary
             pip install streamlit

      - name: Run Python script
        env:
          DB_HOST: ${{ secrets.host }}
          DB_PORT: ${{ secrets.port }}
          DB_NAME: ${{ secrets.database }}
          DB_USER: ${{ secrets.username }}
          DB_PASSWORD: ${{ secrets.password }}
        run: streamlit main_dashboard.py
